// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkMtJllqNfALuMZAeWX_wDH0Uy1xs66YA',
    appId: '1:412313062501:web:09ef9f3101e36c16688a8c',
    messagingSenderId: '412313062501',
    projectId: 'prueba-tecnica-da5c9',
    authDomain: 'prueba-tecnica-da5c9.firebaseapp.com',
    storageBucket: 'prueba-tecnica-da5c9.appspot.com',
    measurementId: 'G-JEJ9Q4WVZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP8n7Y3d00uWwOV6Fo8T5glFbIglm_8uc',
    appId: '1:412313062501:android:74db1b69132c3f42688a8c',
    messagingSenderId: '412313062501',
    projectId: 'prueba-tecnica-da5c9',
    storageBucket: 'prueba-tecnica-da5c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvfxblsWjztIoEoOx6m4z2nmE1YrwL8Yw',
    appId: '1:412313062501:ios:1b46caefc2222d5a688a8c',
    messagingSenderId: '412313062501',
    projectId: 'prueba-tecnica-da5c9',
    storageBucket: 'prueba-tecnica-da5c9.appspot.com',
    iosBundleId: 'com.example.pruebaTecnica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvfxblsWjztIoEoOx6m4z2nmE1YrwL8Yw',
    appId: '1:412313062501:ios:88fb7d6a01379341688a8c',
    messagingSenderId: '412313062501',
    projectId: 'prueba-tecnica-da5c9',
    storageBucket: 'prueba-tecnica-da5c9.appspot.com',
    iosBundleId: 'com.example.pruebaTecnica.RunnerTests',
  );
}
