name: components_ideas
description: Esta es una app donde se agregaran maneras nuevas donde he
  aprendido como hacer cosas nuevas en flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  intl: ^0.19.0
  json_dynamic_widget: ^7.3.1+10
  logger: ^2.5.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_dynamic_widget_codegen: ^1.0.6+15
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
